### ISSUE TITLE
"Error while loading shofel2\imx_usb.bat"

### ISSUE THREAD

**Issue by ethancawse** [rajkosto/TegraRcmSmash#2]
Hello, while installing Linux, I encountered this error: "Error while loading shofel2\imx_usb.bat". Any fast help would be great. Thank you. Here is a photo:
![capture](https://user-images.githubusercontent.com/20261250/40268793-5cfdf23a-5b42-11e8-9ab4-b01b2eff91c6.PNG)

**Comment by CTCaer** [comment]
imx_usb.bat is a batch file not a payload..

**Comment by ethancawse** [comment]
Yes, I understand but when I look inside the folder, it is missing. Was I supposed to download something else? I am assuming that the batch file flashes the Linux kernel.

**Comment by rajkosto** [comment]
None of this is related to TegraRcmSmash.
